In [95]:
import sklearn
import pandas as pd

In [96]:
import nltk
import numpy as np

In [97]:
data = pd.read_csv('reviews.txt', sep="\t", header=None)

data.columns = ['review', 'degree']


reviews = data['review'].copy()
degree = data.review.apply(lambda s : s[0])

data['review'] = reviews.copy()
data['degree'] = degree.copy()

data['review'] = data.review.apply(lambda s: ' '.join(nltk.word_tokenize(s))[1:])

#del reviews
#del degree
data.head(5)
#рейтинг
#0 	negative
#1 	somewhat negative
#2 	neutral
#3 	somewhat positive
#4 	positive

In [105]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.metrics import log_loss
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

In [86]:
pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', MultinomialNB())
])

In [120]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3)

array([ 0.39261863,  0.38797045,  0.39845125])

In [121]:
pipeline = Pipeline([
    ('features', CountVectorizer(analyzer = 'word',                                   
                                    ngram_range=(1, 3),
                                    lowercase=False)),
    ('clf', MultinomialNB())
])

In [122]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3)

array([ 0.37609842,  0.39043264,  0.39669131])

In [139]:
pipeline = Pipeline([
    ('features', CountVectorizer(analyzer = 'word',                                   
                                    ngram_range=(1, 2),
                                    lowercase=False)),
    ('clf', MultinomialNB(alpha = 1))
])

In [140]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3)

array([ 0.38207381,  0.39289483,  0.3907075 ])

In [141]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3,  scoring='neg_log_loss')

array([-3.1479839 , -3.24253191, -3.1854576 ])

In [151]:
from sklearn.linear_model import LogisticRegression
pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', LogisticRegression())
])

In [152]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3,)

array([ 0.38137083,  0.39113612,  0.38859556])

In [153]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3,  scoring='neg_log_loss')

array([-1.50674208, -1.51726239, -1.52788121])

In [156]:
from sklearn.neural_network import MLPClassifier

In [163]:
from sklearn.linear_model import LogisticRegression
pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', MLPClassifier(
                            alpha = 0.1,
                            hidden_layer_sizes = (100,25),
                            activation = 'logistic',
                            max_iter = 230))
])

In [164]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3,)

array([ 0.35606327,  0.36370032,  0.35269271])

In [176]:
pipeline = Pipeline([
    ('features', CountVectorizer()),
    ('clf', LogisticRegression(
                                solver = 'newton-cg'))
])

In [177]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3)

array([ 0.38207381,  0.39183961,  0.38894755])

In [178]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3,  scoring='neg_log_loss')

array([-1.50666288, -1.51716272, -1.52788387])

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [258]:
pipeline = Pipeline([
    ('features', TfidfVectorizer(
                                min_df=3,
                                max_df=0.6,
                                ngram_range=(1, 3),
                                )),
    ('clf', LogisticRegression(
                                solver = 'newton-cg'))
])

In [259]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3)

array([ 0.39543058,  0.40063313,  0.40161915])

In [260]:
cross_val_score(pipeline, data.review, data.degree, cv=3, n_jobs=3,  scoring='neg_log_loss')

array([-1.41849165, -1.41964637, -1.42655623])